// Generated by Glitch!
// Wed Oct 18 20:03:15 2023

#include <AS1115.h>

#include <Wire.h>

auto as  = AS1115(0x00);

auto hours  = 10 * (__TIME__[0] - '0') + (__TIME__[1] - '0');

auto minutes  = 10 * (__TIME__[3] - '0') + (__TIME__[4] - '0');

auto seconds  = 10 * (__TIME__[6] - '0') + (__TIME__[7] - '0');

auto then  = micros();

void prepare_hours(void)
{
 if(hours < 23)
 {
  hours  += (1);
 }
 else
 {
  hours = 0;
 }
}

void prepare_minutes(void)
{
 if(minutes < 59)
 {
  minutes  += (1);
 }
 else
 {
  prepare_hours();
  minutes = 0;
 }
}

void prepare_time(void)
{
}

void prepare_seconds(void)
{
 if(seconds < 59)
 {
  seconds  += (1);
 }
 else
 {
  prepare_minutes();
  seconds = 0;
 }
}

void set_port(const uint8_t i)
{
 Wire.beginTransmission(0x70);
 Wire.write(((uint8_t) 1) << i);
 Wire.endTransmission();
}

void loop(void)
{
 const auto now  = micros();
 if(now - then < 1000000)
 {
  return;
 }
 else
 {
  then = now;
 }
 const auto m1  = micros();
 prepare_time();
 const auto m2  = micros();
 then = ((then) - (((m2) - (m1))));
}

void setup(void)
{
 Wire.begin();
 for(uint8_t i = 0; i < 2; i++)
 {
  set_port(i);
  as.init(3, 0);
  as.clear();
 }
}
