// Generated by Glitch!
// Thu Oct 19 15:48:11 2023

#include <AS1115.h>

#include <RTC.h>

#include <Wire.h>

auto as  = AS1115(0x00);

auto hours  = 10 * (__TIME__[0] - '0') + (__TIME__[1] - '0');

auto minutes  = 10 * (__TIME__[3] - '0') + (__TIME__[4] - '0');

auto seconds  = 10 * (__TIME__[6] - '0') + (__TIME__[7] - '0');

void prepare_time(void)
{
 RTCTime currentTime;
 char a[5] ;
 RTC.getTime(currentTime);
 auto hours  = currentTime.getHour();
 auto minutes  = currentTime.getMinutes();
 auto seconds  = currentTime.getSeconds();
 set_port(0);
 dtostrf((10 * hours + minutes / 10) / 10.0, hours < 10 ? 4 : 3, 1, a);
 as.display(a);
 set_port(1);
 dtostrf((100 * (minutes % 10) + seconds) / 100.0, 3, 2, a);
 as.display(a);
}

void set_port(const uint8_t i)
{
 Wire.beginTransmission(0x70);
 Wire.write(((uint8_t) 1) << i);
 Wire.endTransmission();
}

void loop(void)
{
 prepare_time();
}

void setup(void)
{
 RTC.begin();
 Wire.begin();
 RTCTime time;
 time.setHour(hours);
 time.setMinute(minutes);
 time.setSecond(10 + seconds);
 RTC.setTime(time);
 for(uint8_t i = 0; i < 2; i++)
 {
  set_port(i);
  as.init(3, 0);
  as.clear();
 }
}
